### ISSUE TITLE
Limit requests per minute and user

### ISSUE THREAD

**Issue by Biskit1943** [splitterrust/discord#5]
* A user should only be able to access the Discord bot 5 times a Minute.
* Add an environment variable to overwrite the 5 requests with a custom number

**Comment by Biskit1943** [comment]
* 0 should set this to unlimited

**Comment by queso1307** [comment]
I will have a look into it and decide whether to do this or polish of dice bot first

**Comment by Biskit1943** [comment]
This has to be done in the first instance, before all commands trigger. I might also have a look at this later, so you could do your dice.
